### ISSUE TITLE
Current version doesn't build any more

### ISSUE THREAD

**Issue by adilbaig** [itiu/mongo-d-driver#2]
I assume this is a work in progress. Which is the last revision that can generate the "libmongod-D2.a" file succesfully, for dmd 2.057?

**Comment by adilbaig** [comment]
It turns out i cant compile your code on a 64 bit machine. I can compile the HEAD to x32 using "build.sh" by adding the "-m32" flag

**Comment by shripadk** [comment]
do you intend to support compilation on a 64 bit machine too?
